# -*- coding: utf-8 -*-
"""image_crawling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YyKY3AegxHmIGUD-pbobFf8c85B7kqFY
"""

!pip install beautifulsoup4 requests

!pip install requests

import os

import requests
from bs4 import BeautifulSoup

# 네이버 이미지 검색 결과 페이지 URL
url = "https://search.naver.com/images/search?query=플라스틱컵"  # "검색어"를 원하는 검색어로 대체하세요.

# HTTP GET 요청을 보내고 응답을 받습니다.
response = requests.get(url)

# BeautifulSoup을 사용하여 HTML 파싱
soup = BeautifulSoup(response.text, "html.parser")

# 이미지 URL을 담을 리스트 초기화
image_urls = []

# 이미지 검색 결과에서 이미지 태그 찾기
image_tags = soup.find_all("img")

# 이미지 태그에서 이미지 URL 추출
for img in image_tags:
    src = img.get("src")
    if src:
        image_urls.append(src)

# 이미지 URL 출력
# for img_url in image_urls:
#    print(img_url)

# 이미지를 저장할 디렉토리 생성
os.makedirs("downloaded_images", exist_ok=True)

# 이미지 다운로드 및 저장
for i, img_url in enumerate(image_urls):
    try:
        # 이미지 다운로드
        response = requests.get(img_url)

        # 이미지를 저장할 파일 경로 지정
        file_path = os.path.join("downloaded_images", f"image_{i+1}.jpg")

        # 이미지 파일 저장
        with open(file_path, "wb") as file:
            file.write(response.content)

        print(f"이미지 저장 완료: {file_path}")

    except Exception as e:
        print(f"이미지 저장 실패: {e}")

